#!/bin/bash

# 🚨 RAILWAY RECOVERY SETUP - Senior Developer Emergency Protocol
# Proyecto: apwl-production-v2
# URL: https://railway.com/project/e710d8d7-6d7d-4179-b938-5b867c5188c8

set -e

echo "🚨 RAILWAY RECOVERY - APWL PROJECT"
echo "=================================="
echo "Project: apwl-production-v2"
echo "Project ID: e710d8d7-6d7d-4179-b938-5b867c5188c8"
echo "URL: https://railway.com/project/e710d8d7-6d7d-4179-b938-5b867c5188c8"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Verificar estado actual
echo "🔍 Verificando estado actual..."
railway status

echo ""
echo "📋 MANUAL SETUP REQUIRED:"
echo "========================="
echo ""
echo "1. 🌐 ABRIR RAILWAY DASHBOARD:"
echo "   URL: https://railway.com/project/e710d8d7-6d7d-4179-b938-5b867c5188c8"
echo ""
echo "2. 🗄️ AGREGAR BASE DE DATOS:"
echo "   Click: 'New' → 'Database' → 'Add PostgreSQL'"
echo ""
echo "3. 🔧 CREAR BACKEND SERVICE:"
echo "   Click: 'New' → 'GitHub Repo'"
echo "   Repo: hola-sudo/apwl"
echo "   Root Directory: backend"
echo "   Service Name: backend"
echo ""
echo "4. 🎨 CREAR FRONTEND SERVICE:"
echo "   Click: 'New' → 'GitHub Repo'"
echo "   Repo: hola-sudo/apwl"
echo "   Root Directory: apwl-dashboard"
echo "   Service Name: frontend"
echo ""
echo "5. ⚙️ VARIABLES DE ENTORNO:"

echo ""
echo "   BACKEND VARIABLES:"
echo "   DATABASE_URL=[Auto-generated by PostgreSQL]"
echo "   OPENAI_API_KEY=sk-your-real-key"
echo "   NODE_ENV=production"
echo "   PORT=8080"
echo ""
echo "   FRONTEND VARIABLES:"
echo "   VITE_API_KEY=frontend-admin-key-2024"
echo "   VITE_API_BASE_URL=[Backend URL after deployment]"
echo ""

print_status "Railway project recreated successfully"
print_warning "Manual setup required in Dashboard"
print_status "Project URL: https://railway.com/project/e710d8d7-6d7d-4179-b938-5b867c5188c8"

echo ""
echo "🚀 AFTER MANUAL SETUP - RUN THESE COMMANDS:"
echo "==========================================="
echo "# Link to backend service"
echo "cd backend"
echo "railway service backend"
echo "railway run npx prisma migrate deploy"
echo ""
echo "# Link to frontend service"  
echo "cd ../apwl-dashboard"
echo "railway service frontend"
echo "railway up"

echo ""
print_status "Recovery setup completed. Execute manual steps in Railway Dashboard."